import React, { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import QuizQuestion from '../components/QuizQuestion';
import { API_BASE } from '../config/api';

export default function Quiz() {
  const { token } = useAuth();
  const [topic, setTopic] = useState('JavaScript');
  const [difficulty, setDifficulty] = useState('mixed');
  const [attemptId, setAttemptId] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState({}); // id -> selectedIndex
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState(null);

  const total = questions.length;
  const currentQuestion = useMemo(() => (total > 0 ? questions[current] : null), [questions, current, total]);

  const startQuiz = async () => {
    try {
      setLoading(true);
      setError('');
      setResult(null);
      setAnswers({});
      setCurrent(0);

      const res = await fetch(`${API_BASE}/api/quiz/start`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ topic, difficulty }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.message || 'Failed to start quiz');
      setAttemptId(data.attemptId);
      setQuestions(data.questions || []);
    } catch (e) {
      setError(e.message || 'Could not start quiz');
    } finally {
      setLoading(false);
    }
  };

  const submitQuiz = async () => {
    try {
      setLoading(true);
      setError('');
      const answersArray = Object.entries(answers).map(([id, selectedIndex]) => ({ id, selectedIndex }));
      const res = await fetch(`${API_BASE}/api/quiz/submit`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ attemptId, answers: answersArray }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.message || 'Failed to submit quiz');
      setResult(data);
    } catch (e) {
      setError(e.message || 'Could not submit quiz');
    } finally {
      setLoading(false);
    }
  };

  const onSelect = (idx) => {
    const id = currentQuestion?.id;
    if (!id) return;
    setAnswers((prev) => ({ ...prev, [String(id)]: idx }));
  };

  const onNext = async () => {
    if (current === total - 1) {
      await submitQuiz();
    } else {
      setCurrent((c) => Math.min(c + 1, total - 1));
    }
  };

  const onPrev = () => setCurrent((c) => Math.max(c - 1, 0));

  return (
    <div className="min-h-screen bg-slate-50 py-8 w-full">
      {/* Header */}
      <div className="w-full px-6 text-center mb-8">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Topic Quiz</h1>
        <p className="text-slate-600">Choose a topic and take a 10-question quiz generated by our AI.</p>
      </div>

      {/* Full-width Container */}
      <div className="w-full bg-white shadow-lg px-6 py-8">
        {/* Controls */}
        {!attemptId && !result && (
          <div className="grid gap-4 md:grid-cols-3 items-end">
            <div className="flex flex-col text-left">
              <label className="text-sm text-slate-600 mb-1">Topic</label>
              <input
                className="border border-slate-200 rounded px-3 py-2"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. JavaScript, Data Structures, History"
              />
            </div>
            <div className="flex flex-col text-left">
              <label className="text-sm text-slate-600 mb-1">Difficulty</label>
              <select className="border border-slate-200 rounded px-3 py-2" value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                <option value="mixed">Mixed</option>
                <option value="easy">Easy</option>
                <option value="medium">Medium</option>
                <option value="hard">Hard</option>
              </select>
            </div>
            <div>
              <button onClick={startQuiz} disabled={loading} className="w-full px-4 py-2 rounded bg-blue-600 text-white disabled:opacity-50">{loading ? 'Starting...' : 'Start Quiz'}</button>
            </div>
          </div>
        )}

        {error && (
          <div className="mt-4 p-3 bg-red-50 border border-red-200 text-red-700 rounded">{error}</div>
        )}

        {/* Quiz */}
        {attemptId && !result && currentQuestion && (
          <div className="mt-8">
            <QuizQuestion
              index={current}
              total={total}
              question={currentQuestion}
              selectedIndex={answers[String(currentQuestion.id)]}
              onSelect={onSelect}
              onNext={onNext}
              onPrev={onPrev}
              submitting={loading}
            />
          </div>
        )}

        {/* Result */}
        {result && (
          <div className="mt-8">
            <div className="bg-white rounded-lg shadow p-6">
              <h2 className="text-xl font-semibold text-slate-900 mb-2">Your Score</h2>
              <p className="text-slate-700 mb-4">{result.score} / {result.total}</p>
              <div className="space-y-4">
                {result.review.map((r, i) => (
                  <div key={i} className="border border-slate-200 rounded p-4">
                    <div className="font-medium text-slate-900 mb-1">Q{i+1}. {r.prompt}</div>
                    <ul className="list-disc ml-6 text-slate-700">
                      {r.options.map((opt, idx) => (
                        <li key={idx} className={`${idx === r.correctIndex ? 'text-green-700' : ''} ${idx === r.selectedIndex && idx !== r.correctIndex ? 'text-red-700' : ''}`}>
                          {String.fromCharCode(65 + idx)}. {opt}
                        </li>
                      ))}
                    </ul>
                    <div className="mt-2 text-slate-600">
                      <span className="font-semibold">Explanation:</span> {r.explanation}
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-6 flex gap-3">
                <button onClick={() => { setAttemptId(null); setQuestions([]); setResult(null); }} className="px-4 py-2 rounded bg-slate-100 text-slate-700">New Topic</button>
                <button onClick={startQuiz} className="px-4 py-2 rounded bg-blue-600 text-white">Retake</button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
